### PR TITLE
Getting Started and learning React + NextJS

### PR DESCRIPTION
**Pull request by francisaguilar21**
I just finished the module **From React to NextJS** found at the nextjs [website](https://nextjs.org/learn/foundations/from-react-to-nextjs).

### CODE REVIEW

**Comment by francisaguilar21** [comment]
Linked the first item in the project board -- #2 Learn React + NextJS

**Comment by francisaguilar21** [comment]
# How NextJS Works (https://nextjs.org/learn/foundations/how-nextjs-works)

The main things I were blown away when I was reading about how NextJS work were:
1. You can choose which pages would be pre-rendered and the method how they would be rendered -- SSR (server side rendering) or SSG (static site generation).
2. I was blown away how there was a concept such as Incremental Static Regeneration (ISR) wherein you don't need to rebuild everything. You can just a pick specific ones you want to update.
3. I was only familiar with the concept of CDNs but **Edge** is super amazing on how it can BOTH cache and execute code while being available all over the Globe.

**Comment by francisaguilar21** [comment]
# Create Your First App (https://nextjs.org/learn/basics/create-nextjs-app)

Things worth taking note of 🤯 

## Navigating Between Pages (https://nextjs.org/learn/basics/navigate-between-pages/link-component)
1. NextJS takes care of the optimizations for navigation through **code splitting** and **prefetching**. The items are prefetched in the background even before you click on the link. 

## Assets & Metadata (https://nextjs.org/learn/basics/assets-metadata-css)
1. NextJS has their own components for everything in order to optimize it!!! For example in the `Image` component, it automatically optimizes it by serving it in **Webp** and offering lazy loading for the image by default.
2. Adding to the point above, the built in components make it easy for making the developer experience a lot easier. Take the case with the `Head` component, it automatically updates the metadata based on the provided `<title></title>` and other info.
3. You can only import global styles in one file -- `pages/_app.js`
4. NextJS supports a lot of packages out of the box like sass, Postcss, tailwind, etc but you would need to first install them via npm or yan in order to be included in the package.json. After that, you would need to make changes in the `nextjs.config.js`. With Angular, a lot of these is already installed upon app creation which can be a plus or not depending on how you're looking at it.

**Comment by francisaguilar21** [comment]
## Pre-rendering and Data-fetching (https://nextjs.org/learn/basics/data-fetching)

1. You can pre-render not only through just SSG or SSR but having them both work in app as hybrid is feasible.
2. [Static Generation](https://nextjs.org/docs/basic-features/pages#static-generation-recommended) can be done with and without data.
3. Code that are written to be pre-rendered through SSG are not even included in the bundle that gets sent to the browser despite it being part of the project. WOW!

## Extra
[SWR](https://swr.vercel.app/ ) is a React hook for data fetching. It handles caching, revalidation, focus tracking, refetching on interval, and more.

## Dynamic Routes (https://nextjs.org/learn/basics/dynamic-routes/)

1. You can generate pages with dynamic routes through SSG with `getStaticPaths()` & `getStaticProps()`.
2. `getStaticPaths()` can even handle arrays such as `/posts/a`, but also `/posts/a/b`, `/posts/a/b/c` and so on, it just needs to follow this format (`pages/posts/[...id].js matches`). It matches all of the possibilities mentioned.

**Comment by francisaguilar21** [comment]
## API Routes (https://nextjs.org/learn/basics/api-routes/api-routes-details)

1. You can apparently create an API with the NextJS as well similar to the old ASP.NET Web MVC framework that I used to work on.
2. API routes can also be dynamic similar to the previous section -- Dynamic Routes. It's called **Dynamic API Routes**. (https://nextjs.org/docs/api-routes/dynamic-api-routes)
3. API Routes work hand-in-hand with a concept called **Preview Mode** which can give you a draft preview of a page generated upon request time and **not during build time** when you don't want it to be published yet. (https://nextjs.org/docs/advanced-features/preview-mode)

## Deploying your NextJS App (https://nextjs.org/learn/basics/deploying-nextjs-app)

1. Vercel has this process called DPS (Develop, Preview, Ship) workflow wherein every time you push to a branch, it creates a preview that you can share with other collaborators in order to get immediate feedback. 💯

**Comment by FrancisAguilar21** [comment]
## Deploying your NextJS App (https://nextjs.org/learn/basics/deploying-nextjs-app)

1. Vercel has this process called DPS (Develop, Preview, Ship) workflow wherein every time you push to a branch, it creates a preview that you can share with other collaborators in order to get immediate feedback. 💯

**Pull request merged**
